# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20170220_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='db',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='model',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
