# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20170221_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
