# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_user_registered_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
